### ISSUE TITLE
paint.net-wic-plugin does not load alpha channel properly

### ISSUE THREAD

**Issue by pps83** [ReneSlijkhuis/example-wic-applications#1]
The issue is for [paint.net-wic-plugin](https://github.com/ReneSlijkhuis/paint.net-wic-plugin).
Looks like it does not handle alpha channel properly, images look completely messed up when loaded in paint.net using paint.net-wic-plugin.

Attached zip contains identical webp and png images. WIC plugin for webp images is here:
https://storage.googleapis.com/downloads.webmproject.org/releases/webp/WebpCodecSetup.exe

Both of these images are 100% identical, but when test.webp is loaded it has black background in place of transparent regions.

[test.zip](https://github.com/ReneSlijkhuis/example-wic-applications/files/1238039/test.zip)

**Comment by ReneSlijkhuis** [comment]
Thanks for reporting. I will have a look at this issue.

**Comment by ReneSlijkhuis** [comment]
I've fixed this issue. Thanks again for reporting. A new version is available here:
[https://forums.getpaint.net/topic/111550-windows-imaging-component-wic-plugin/](https://forums.getpaint.net/topic/111550-windows-imaging-component-wic-plugin/)

**Comment by pps83** [comment]
Thanks, works perfectly now.
